apiVersion: v1
kind: Service
metadata:
  name: front
  labels:
    app: front
    service: front
spec:
  type: ClusterIP
  selector:
    app: front
  ports:
  - name: http
    port: 8080
    targetPort: 8080
